使用方法:
 1.命令ee.
  2.输入编号,为数字,用这个数字来开关显示所选的图形.
   3.选择图形.
输入命令:(刚刚你在第2步里面所输入的数字)则隐藏图形.
两次输入命令::(刚刚你在第2步里面所输入的数字)则显示图形.

把以下文件保存为 .lsp文件,用CAD加载即可食用,无需冷藏!.
[quote]
;隐藏或显示部分图形
;作者wujimmy  来自:http://www.wujimmy.com
(setq wjm_hide_lst nil)
(defun c:ee()
  (setq index_num (getint "图形组编号:"))
  (princ "\n选择要显示或隐藏的图形:")
  (setq es (ssget))
  (if es
    (progn
  
  (if (assoc index_num wjm_hide_lst)
    (progn
      (if (null(caddr(assoc index_num wjm_hide_lst))) (wjm_show_hide index_num) );_如果原来图层是关着的,就打开显示.
      (setq wjm_hide_lst (subst (list index_num es t)(assoc index_num wjm_hide_lst) wjm_hide_lst )))
    (setq wjm_hide_lst (append wjm_hide_lst (list (list index_num es t))))
    )
  (eval (read (strcat"(defun c:" (rtos index_num 2 0)"() (wjm_show_hide "(rtos index_num 2 0) "))")))
  )
  )
  )

(defun wjm_show_hide(index_num / i% es index_num mid isShow )
  ;(setq index_num 1)
  (setq mid (assoc index_num wjm_hide_lst))
  (setq es (cadr mid))
  (setq isShow (null (caddr mid)))
  (setq wjm_hide_lst (subst (list index_num es isShow)(assoc index_num wjm_hide_lst) wjm_hide_lst ))
  (setq i% 0)
   (repeat (sslength es)
     (if isShow
       (redraw (ssname es i%)  1)
       (redraw (ssname es i%)  2)
       )
     (setq i% (1+ i%))
   )
  (if isShow
       (princ "\n已经全部显示!")
       (princ "\n已经全部隐藏!")
       )
  (princ)
  )

[/quote]