这里是最新版,功能强化了很多:
[file=uploads/200609/15_013853_黄金左手20060915.rar]2006,09,15更新下载[/file]
[quote]
===>黄金左手程序说明<===
    本程序是通过输入数字或字母代替代替输入钢筋根数及直径

    以减少用户输入钢筋是的繁杂钢筋输入过程.
    以下是钢筋直径,钢筋根数对照表.
直径:a=14,b=16,c=18,d=20,e=22,f=25...
根数:a=1,b=2,c=3,d=4,e=5,f=6...使用程序中有几点要注意的问题,了解这些问题将有利于
你更好的使用本程序.
      
1.程序运行过程中会自动查找梁线,用于判断梁宽,从而可以自动加上钢筋排数信息,目前只
支持二排筋.
      2.程序识别的梁线的图层为"*梁*,*beam*,bout " 其中*可以是任意字符,
       例如你的梁线图层为"梁实线",则会被程序所支持.
      
3.另外,为了保持程序对各种比例的图形都能识别出梁宽,在命令运行过程中按右键可以设置
图形比例.
      4.右键菜单中还可以设置保护层厚度.
      5.本程序还在不断优化中,以期使你的画图效率得到极大的提高,
        请继续关注官方网站中"结构软件"版块的最新态
        网址http://www.wujimmy.com
      6.如果你想改变程序默认的钢筋直径,钢筋根数对照表,
        你可以修改文件cc-user.lsp中的相应内容,
        并把该文件置于AutoCAD的支持目录下(例如support这个目录).
      7.本程序作者 吴所不及,如有转载请注明作都及官方网址等信息!
            未经许可,本程序不得用于任何商业软件.

更多惊喜等着你,赶快行动吧......
[/quote]

[file=uploads/200609/13_132929_梁筋修改=黄金左手.rar]点击下载[/file]

[img]http://wjmcad.googlepages.com/gif.jpg [/img]

使用a b c ...代表 1 2 3....  , 14 16 18.....
对于使用左手操作键盘,右手鼠标,的速度有一定的提高
因为数字键都在上面,很难够的着,而且容易打错了

;(PRINC "文字工具，Version 1.00, 版权(c) 2005.03.27 Lin.T.Y, Inc. ")
;(PRINC "\n选择要修改的注释对象。")
;(princ " hb 文字合并； he 文字绝对值求和。")
;(princ " tt 修改钢筋")
;;;修改日期:2005.12.12

(defun c:hb ()
  (princ "选择要合并的文字")
  (setq	sset (ssget
	       '((0 . "TEXT"))
	     )
  )
  (setq	text ""
	i 0
  )
  (setq first (entget (ssname sset 0)))
 (repeat (sslength sset)
   (progn
     (setq text	(strcat
		  text
		  (cdr
		    (assoc 1
			   (entget (ssname sset i)
			   )
		    )
		  )
		  
		)
     )
     (entdel (ssname sset i))
   )
   (setq i (+ 1 i))
 )
  (entmake (subst (cons 1 text) (assoc 1 first) first))
  (princ text)
)
;;;文字绝对值求和
(defun c:he()
  (princ "选择要求和的文字字")
  (setq	sset (ssget
	       '((0 . "TEXT"))
	     )
  )
  (setq	sum 0
	i 0
  )
  (setq first (entget (ssname sset 0)))
 (repeat (sslength sset)
   (progn
     (setq sum (+
		  sum
                 (abs
		   (atoi 
                     (cdr
		           (assoc 1
			    (entget (ssname sset i)
			   )
		     )
		   )
		  
		 )
                   )
               )
     )
     
   )
   (setq i (+ 1 i))
 )  
  (princ sum)
  (princ)
)

(defun cht_Edit	(objs	n_str  /      last_o tot_o  ent	   o_str
		 st	s_temp n_slen o_slen si	    chf	   chm
		 cont	ans    class
		)

  (setq class (cdr (assoc 0 (setq ent (entget objs)))))
  ;;if
  (if (or (= "TEXT" class)
	  (= "MTEXT" class)
      )
    (progn
      (setq chf	nil
	    si	1
      )
      (setq s_temp (cdr (assoc 1 ent)))

      (while (and (/= "(" (substr s_temp si 1)) (< si 10))
	(setq si (1+ si))

      )

      (setq s_temp (strcat
		     n_str
		     (substr s_temp si)
		   )
      )
      (progn ;; Substitute new string for old
	     ;; Modify the TEXT entity
	     (entmod (subst (cons 1 s_temp) (assoc 1 ent) ent))

      )

    )

  )

)

;|
(defun c:cc ()  
  
  (setq	text ""
	i 0
	str-lst (list "A" "B" "C" "D" "E" "F" "G" "H" "I" "1" "2" "3" "4" "5" "6" "7" "8" "9" "N" "G")
  )
  (setq ent (entget(car(my_EntSel "选择要修改的文字" '((0 . "TEXT"))))))
  (setq	str
	 (cdr
	   (assoc 1
		  ent
	   )
	 )
  )

  (cond

    ((wcmatch str "`%`%13*`@*`([2-6]`)")
     (princ "箍筋:")
     (princ str)
     (cond
       ((wcmatch str "`%`%13[1-4]#@*,`%`%130##@*")
	(alert (strcat "箍筋错误:" str))
       )
     )
    )
    ((wcmatch str "*`%`%13[1-4]##[~@]*,*`%`%13[0-4]#[~@]*")

     (princ "\n钢筋面积是:")
     (princ (str-to-area str))

;;;     (setq mod (grread nil 10 0))
;;;     (cond
;;;       ((= (car mod) 2)
;;;	 (foreach cha str-lst)
;;;	     (if(= (strcase (chr (cadr mod))) cha) )
;;;	)
;;;       
;;;       )
;;;     );_cond
  
     (setq p1 (strcat "A B C D E F G H I 1 2 3 4 5 6 7 8 9 N GG_1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 N" strl " G" strl)) 
     (initget
       p1
     )
     (setq p1 (strcat  "\n钢筋根数\n[1 2 3 4 5 6 7 8 9]\n[A B C D E F G H I]<" strl ">:"))
     (setq num (getkword p1))
     (if (= num nil)
       (setq num strl)       
     )

     (initget
       "A B C D E F 14 16 18 20 22 25_14 16 18 20 22 25 14 16 18 20 22 25"
     )
     (setq p1 (strcat "\n钢筋直径\n[14 16 18 20 22 25]\n[A  B  C  D  E  F]<" strr ">:"))
     (setq rad (getkword p1))
     (if (= rad nil)
       (setq rad strr)
     )
     
     (setq text (strcat num steel rad))

    )

  )

  (entmod (subst (cons 1 text) (assoc 1 ent) ent))
  (princ text)
)

|;
(defun getab (str / add-pos )
  
 (cond
       ((wcmatch str "*`%`%130*")
	(setq steel "%%130")
       )
       ((wcmatch str "*`%`%131*")
	(setq steel "%%131")
       )
       ((wcmatch str "*`%`%132*")
	(setq steel "%%132")
       )
       ((wcmatch str "*`%`%133*")
	(setq steel "%%133")
       )
       ((wcmatch str "*`%`%134*")
	(setq steel "%%134")
       )
       (T (setq steel "%%132"))
     )
  
  (setq str (vl-string-subst " " "%%130" str))
  (setq str (vl-string-subst " " "%%131" str))
  (setq str (vl-string-subst " " "%%132" str))
  (setq str (vl-string-subst " " "%%133" str))
  (setq str (vl-string-subst " " "%%134" str))
  (setq str (vl-string-subst "" "G" str))
  (setq str (vl-string-subst "" "N" str))
  
  
  (setq add-pos (vl-string-position (ascii " ") str))
  (if add-pos
    (progn
      (setq strl (substr str 1 add-pos))
      (setq strr (substr str (+ 2 add-pos)))
      (eval
	(list *
	      (atof strl)
	      (* pi
		 (* (/ (atof strr) 2)
		    (/ (atof strr) 2)
		 )
	      )
	)
      )
    )
    (progn
      (+ 0 0)
    )
  )

)

(defun C:test ( / pt1) 

  (initget 128)					; 设定任意输入位值
  (setq pt1 (getpoint "\nPoint: "))			; 获取用户输入
  (if (= 'STR (type pt1))				; 若是字符串，则将它转换为一个符号，
    (setq pt1 (eval (read pt1)))			; 并把它当作函数试着求值；
						; 否则，
    pt1					; 只返回该数值。
  )
)
(defun REF ( )
  (setvar "LASTPOINT" (getpoint "\nReference point: "))
  (getpoint "\nNext point: " (getvar "LASTPOINT"))

)

(defun c:cc ()
  (princ "选择要修改的文字")

  (setq	sset (ssget
	       '((0 . "TEXT"))
	     )
  )
  (setq	text ""
	i 0
  )
  (setq ent (entget (ssname sset 0)))
  (setq	str
	 (cdr
	   (assoc 1
		  ent
	   )
	 )
  )

  (cond

    ((wcmatch str "`%`%13*`@*`([2-6]`)")
     (princ "箍筋:")
     (princ str)
     (cond
       ((wcmatch str "`%`%13[1-4]#@*,`%`%130##@*")
	(alert (strcat "箍筋错误:" str))
       )
     )
    )
    ((wcmatch str "*`%`%13[1-4]##[~@]*,*`%`%13[0-4]#[~@]*")

     (princ "\n钢筋面积是:")
     (princ (getab str))
     (setq p1 (strcat "A B C D E F G H I 1 2 3 4 5 6 7 8 9 N GG z_2 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 N"strl" G"strl" K")) 
     (initget
       p1
     )
     (setq p1 (strcat  "\n钢筋根数\n[1 2 3 4 5 6 7 8 9 Z     ]\n[A B C D E F G H I 加括号]<" strl ">:"))
     (setq num (getkword p1))
     (if (= num nil)
       (setq num strl)
     )
     (if (eq num "K")
       (setq text (strcat "(" str ")"))
       (progn
	 (initget
       "A B C D E F 14 16 18 20 22 25 Z_14 16 18 20 22 25 14 16 18 20 22 25 16"
          )
        (setq p1 (strcat "\n钢筋直径\n[14 16 18 20 22 25]\n[A  B  C  D  E  F]<" strr ">:"))
         (setq rad (getkword p1))
         (if (= rad nil)
           (setq rad strr)
         )
	 (cond
	   ((<= (atof num) 3) (setq rad (rtos (atof rad) 2 0)))
	   ((and (eq num "4") (<= (atof rad) 16))  (setq rad (rtos (atof rad) 2 0)))
	   ((and (eq num "4") (> (atof rad) 16)) (setq rad (strcat rad " 2/2")))
	   ((eq num "5") (setq rad (strcat rad " 3/2")))
	   ((eq num "6") (setq rad (strcat rad " 4/2")))
	   )

	 (setq text (strcat num steel rad))
        );_progn
       )
    )
  )
  (entmod (subst (cons 1 text) (assoc 1 ent) ent))
  (princ (strcat "\n修改后钢筋面积是:" (rtos (getab text) 2 0) "mm" ))
  (princ)
)

[file=uploads/200604/26_213952_text050327.rar]点击下载[/file]