使用方法:
 1.命令ee.
  2.输入编号,为数字,用这个数字来开关显示所选的图形.
   3.选择图形.
输入命令:(刚刚你在第2步里面所输入的数字)则隐藏图形.
两次输入命令::(刚刚你在第2步里面所输入的数字)则显示图形.

把以下文件保存为 .lsp文件,用CAD加载即可食用,无需冷藏!.
[quote]
;隐藏或显示部分图形
;作者wujimmy  来自:http://www.wujimmy.com
(setq wjm_hide_lst nil)
(defun c:ee()
  (setq index_num (getint "图形组编号:"))
  (princ "\n选择要显示或隐藏的图形:")
  (setq es (ssget))
  (if es
    (progn
  
  (if (assoc index_num wjm_hide_lst)
CAD的几个命令,可以在执行命令的时候,动态显示.
可以实时看到显示效果,实在是众编程者所要的那种效果.

这种效果,用OBJECTARX来实现是比较简单的.

不过用AUTOLISP实现起来就有点吃力了.
因为要不断的entmod实体,实在是比较慢,而且会卡.一闪一闪的.

今天发现一个现像,我的用移动命令的时候,把东西移动到标注上,不小心,死了.
结果CAD死了.我点了保存文件(2002可以保护为新的文件,所以就保存了).

又得重新开CAD,打开原来的图,看看,还差好多.想想还是修复一下算了.
还好能用,只查出了一个错误就好了.

什么,有一个错误,什么错误?速速报来!

[quote]
发现无效的块名“”。
改为“AUDIT_I_060923095030-0”。
[/quote]

无效块?哪里来的块?莫非是.....
没错,就是那个命令COPY生成的,生成一半死掉了,还来不及删掉就被CAD保存下来了.
