[quote](vl-load-com)
(defun C:jm (/ BLK BLKDEF BLKREF)
  (print "请选择加入块的对象:")
  (setq ss1 (ssget))
  (command "block" "aa$1" "0,0" ss1 "")
  (command "insert" "aa$1" "0,0" "" "" "")
  (setq el (entlast))
  (command "minsert" "aa$1" "0,0" "" "" "" "" "2" "0")
  (setq BLKREF (vlax-ename->vla-object el))
  (setq
    BLKDEF (vla-item (vla-get-blocks
		       (vla-get-activedocument (vlax-get-acad-object))
		     )
		     (vla-get-name BLKREF)
	   )
  )
  (vla-put-name BLKDEF "*U")
  (vlax-release-object BLKREF)
  (vlax-release-object BLKDEF)
  (command "erase" el "")
  (princ)
)
(princ "加密:jm")
[/quote]