(defun c:jfz (/ 2d1 2d10 2d11 7d 8d d1 d10 d11 d40 d50 dd dis1 dis2 dxf dxf2
		en en2 i ii line1 line2 p1 p2 ss ss2 str textdxf)
  (setvar "cmdecho" 0)
  (setq @os (getvar "osmode"))(setvar "osmode" 0)  	     
  (command ".undo" "be")
  (setq ss (ssget '((0 . "text") (1 . "(*号)"))))
  (setq i -1)
  (while (setq en (ssname ss (setq i (1+ i))))
    (setq dxf (entget en)
	  7d (assoc 7 dxf)
应网友要求,定做了这个程序:

[quote]
(princ "\t\t\t\t吴极工具箱之<基础内力叠加(+-*/)程序>\n
程序启动命令:jct1
程序说明:jcth1
如果觉得命令太长,请自行定义CAD的support目录中的acad.pgp文件.

版权所有[吴所不及]www.jgcad.com\n
       \t\t\t\t----2007-0621")

(defun c:jcth1()

  (princ "\t\t\t\t吴极工具箱之<基础内力叠加(+-*/)程序>\n
程序启动命令:jct1
程序说明:jcth1

使用时,先把第一个操作数所在的图指定为蓝色(不是图层),然后把两张及以上的图叠在一起.

如果觉得命令太长,请自行定义CAD的support目录中的acad.pgp文件.

版权所有[吴所不及]www.jgcad.com\n
