[quote]

;;*********************************转载请注明****************************
;;原文地址:http://www.jgcad.com/article.asp?id=268
;;程序功能:插入PKPM所有计算结果到当前图纸,要求先进行图纸转换成DWG文件.
;;作者:吴所不及.
;;版权所有[结构CAD]http://www.jgcad.com
;;本站致力于结构画图软件开发,极力于提高结构师的画图效率.
;;如果你有什么好的建议,请告诉我们.
;;*********************************转载请注明****************************

(VL-LOAD-COM)

(setq paper-dist 2000);_图纸之间距离.
(defun c:jss()
    (init_bonus_error 
    (list
      (list "cmdecho" 0 "osmode"  0
      )
      T     ;flag. True means use undo for error clean up.
    );list  
  )

  (alert "\n该函数用于生成所有的计算书.")

;;;        (initget "Y N_Yes No")
;;;      (setq changepos (getkword "\n是否插入到同一点?[Y/N]<Y>:"))
;;;      (if (null changepos) (setq changepos "Yes"))

  (setq dir-mid (qf_getFolder (strcat"选择文件夹<" (if filedir filedir "")">:")))
  (if dir-mid (setq filedir dir-mid)) 
  
  (command "layer" "m" "plot" "")
  (setq pt-start (getpoint))

  ;;荷载. "第_1层梁、墙柱节点输入及楼面荷载平面图.DWG"
  
  (setq file-list (vl-directory-files filedir "第??层梁、墙柱节点输入及楼面荷载平面图.DWG"))
  (if file-list (setq max-distx (my_insert pt-start file-list 1)))
  (setq pt-start (polar pt-start 0 max-distx))

  ;;板筋;bjss板计算结果01.DWG
    (setq file-list (vl-directory-files filedir "*板计算结果*.dwg"))
  (if file-list (setq max-distx (my_insert pt-start file-list 100)))
  (setq pt-start (polar pt-start 0 (+ paper-dist max-distx)))

  ;;梁筋;
  (setq file-list (vl-directory-files filedir "wpj*.dwg"))
  (if file-list (setq max-distx (my_insert pt-start file-list 1000)))
  (setq pt-start (polar pt-start 0 (+ paper-dist max-distx)))

  ;;梁截面;

  (setq file-list (vl-directory-files filedir "FLR*.dwg"))
  (if file-list (setq max-distx (my_insert pt-start file-list 1000)))
  (setq pt-start (polar pt-start 0 (+ paper-dist max-distx)))
  
  )

;;;(str-to-num "第11层梁、墙柱节点输入及楼面荷载平面图.DWG")

(defun str-to-num (str1)

  (setq n 0)
  (setq s1 "")
  (while
    (if	(and (/= "" (setq cha (substr str1 (setq n (1+ n)) 1))))

      (if (wcmatch cha "#")
	(setq s1 (strcat s1 cha))
	(if (/= s1 "")
	  nil
	  t
	)
      )
      nil
    )
  )
  (setq num1 (atoi s1))

)
(defun my_insert (pt file-list scale)
  (setq diet 0)
  (setq x (car pt)
	y (cadr pt))
  (setq max-distx 0)

  (setq
	file-list (vl-sort
		   file-list
		   (function
		     (lambda (str1 str2)		       
			(< (str-to-num str1 )
		       (str-to-num str2 ))
			   )
		       
		     );_lambda
		   );_function
		 )
  
  (foreach filename file-list
    (progn      
      
	(command
	  "_insert"
	  (strcat filedir "\\" filename)
	  (list x y 0)
	  scale
	  scale
	  0
	)
	(progn
	(setq newen1 (entlast))
	(setq obj (vlax-ename->vla-object newen1))
        (vla-getboundingbox obj 'll 'ur)
        (setq pt1 (vlax-safearray->list ll))
        (setq pt2 (vlax-safearray->list ur))
	
	(vl-cmdf ".rectangle" (polar pt1 -3.14 1000) pt2)
	(setq newen2 (entlast))
	(setq obj (vlax-ename->vla-object newen2))
	(vla-put-color obj acBlue)
	
	(entmake (list
	       (cons 0 "TEXT")
	       (cons 1 filename)
	       (cons 40 350.0)
	       (cons 41 0.7)
	       (cons 10 (polar pt1 (* 0.5 pi) 1000))
	       (cons 50 (/ pi 2))
	       (cons 8 "filename")
	       (cons 7 "STANDARD")	       
	       ))
	(setq newen3 (entlast))

	(command "_.move" newen1 newen2 newen3 "" pt1 (list x y 0))
	
	(setq distx (- (car pt2) (car pt1)))
	(setq disty (- (cadr pt2) (cadr pt1)))

	(setq max-distx (max distx max-distx))	
	(setq y (+ disty y paper-dist));_增加图的y坐标.
	

	;(command "scale" newen "" (midpt pt1 pt2) 1.02);_外框放大.
	)
	(princ (strcat "\n" filedir filename))	
      )
    )
  max-distx
  )
  
[/quote]