[quote]
;;集中标注处理序
;;显示特殊的标注,比如有标注数值与长度差别比较多的.比例不是多少的.==
(defun c:dimcheck()
   (setq wjm_dc_check_diet (getint "\n输入误差值:"))
   (princ "\n选择标注:")
   (setq ss (ssget (list (cons 0 "DIMENSION"))))
  
   (if (ssget "X" (list (cons 8 "wujimmy_dc_Error")))
	(progn	  
	  (command "erase" "P" "")	  
	)
      )
   (setq errornum 0)
   (while (and ss (setq en (ssname ss 0)))
     (ssdel en ss )(setq ent (entget en))
     (setq text (cdr (assoc 1 ent)))

     	 (setq text_value(atof text))
	 (setq pt1 (cdr (assoc 10 ent)));_标注上面的那个点
	 (setq pt2 (cdr (assoc 14 ent)));_标注终点,对应于上面那个点
	 (setq mid_point (cdr (assoc 13 ent)));_标注的起点
	 (setq	pt_dist (* (sin (- (angle mid_point pt1)
			    (angle mid_point
				   pt2
			    )
			 )
		    )
		    (distance mid_point pt1)
		    (distance mid_point pt2)
		    (/ 1 (distance pt1 pt2))
		 )
          );_三角形公式求边长.
         (setq pt_dist (abs pt_dist))
	 (princ "\n距离是:")
	 (princ pt_dist)(princ "\t")

     
     (if (/= text "")
       (progn	 
	 (if (equal text_value pt_dist wjm_dc_check_diet) (+ 1 1)
	   (progn	     
	     (dc-printerror (cdr (assoc 11 ent)) (strcat "实际尺寸是:"
						   (rtos pt_dist)
	                                            "\n标注尺寸是:"
	                                           text))
	     )
	   )
	 ))
     );_while
  (princ "\n错误个数是:")
  (princ errornum)
  (princ)
  )

(regapp "PE_URL")
(defun dc-printerror (pt errortext / ent)
  (if (null errornum) (setq errornum 0))
 (setq ent(entmakex
	    (list (cons 0 "CIRCLE")
		  (cons 8 "wujimmy_dc_Error")
		  (cons 40 (+ 800 (* 100 (rem errornum 5))))
		  (cons 10 pt);_标注文字所在的点.
		  (list -3 (list "PE_URL" (cons 1000 errortext)))
	    )
	  ))
  (setq errornum (1+ errornum))
  ent
)

[/quote]